//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WereViewApp.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscribeNotifiedHistory
    {
        public long SubscribeNotifiedHistoryID { get; set; }
        public long SubscribeID { get; set; }
        public System.DateTime NotifiedOnDate { get; set; }
    
        public virtual Subscribe Subscribe { get; set; }
    }
}
