//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace WereViewApp.Models.EntityModel.POCO
{
    public partial class Category
    {
        public Category()
        {
            this.Apps = new HashSet<App>();
        }
    
        public short CategoryID { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<App> Apps { get; set; }
    }
}
