//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web;
using WereViewApp.Modules.Uploads;

namespace WereViewApp.Models.EntityModel.POCO
{
    public partial class Gallery : IUploadableFile
    {
        public Guid GalleryID { get; set; }
        public Guid UploadGuid { get; set; }
        public int GalleryCategoryID { get; set; }
        public byte Sequence { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }

        public HttpPostedFileBase File { get; set; }

        public string Extension { get; set; }

        public virtual GalleryCategory GalleryCategory { get; set; }


       
       

        //public IImageCategory Category {
        //    get {
        //        return this.GalleryCategory;
        //    }             
        //}


        
    }
}
